global:
  scrape_interval:     15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'enable-prometheus-kieserver'
    metrics_path: /services/rest/metrics
    basic_auth:
      username: adminUser
      password: RedHat
    static_configs:
    - targets: ['enable-prometheus-kieserver:8080']
