apiVersion: v1
kind: Service
metadata:
  annotations:
    description: RHPAM Prometheus metrics exposed
  labels:
    app: enable-prometheus-kieserver
    application: enable-prometheus-kieserver
    template: enable-prometheus-kieserver
    metrics: rhpam
  name: rhpam-app-metrics
spec:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    deploymentConfig: enable-prometheus-kieserver
  sessionAffinity: None
  type: ClusterIP
