kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gps-h2-claim-v110
  namespace: dev-pam
  labels:
    app: custom-kieserver-kjar-a
    application: custom-kieserver-kjar-a-v110
    rhpam: '7.6.0'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
