//created on: 18-Nov-2016
package com.skoussou.brms.central;

//list any import classes here.
import com.skoussou.brms.*;



//declare any global variables here


/* -------- BUILDING ACTIVITY PERMIT RULES -------- */
rule "(CENTRAL) - building-activity permit"
//agenda-group "building-activity-central"

agenda-group "building-activity"
salience 100
//lock-on-active true
when
	$b : BuildingStructureActivity()
	not IsPermitRequired(activity == $b)
	LegalApplicability( activity == $b)
	BuildingStructureActivity( size.squareMeters > 100 );
    $results : BRMSEngineResults()	
then
	//System.out.println("      (CENTRAL) - building-activity permit required");
	$results.getPermits().add(new Permit($b.getType().name(), "CENTRAL"));	
end
