{
 "title": "RHPAM Process & Task Monitoring",
 "tags": [ "RHPAM" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Self-Eval Tasks Status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kie_server_task_added_total{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"HR Evaluation\",}",
     "legendFormat": "Openned Self-Evals"
    },
    {
     "expr": "kie_server_task_completed_total{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"HR Evaluation\",}",
     "legendFormat": "Completed Self-Evals"
    }
   ]
  },
  {
   "title": "Task Execution Times",
   "type": "gauge",
   "gridPos": { "h": 17, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "kie_server_task_duration_seconds_count{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"Self Evaluation\",}",
     "legendFormat": "Time for Self Eval Task (secs)"
    },
    {
     "expr": "kie_server_task_duration_seconds_count{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"PM Evaluation\",}",
     "legendFormat": "Time for PM Eval Task (secs)"
    },
    {
     "expr": "kie_server_task_duration_seconds_count{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"HR Evaluation\",}",
     "legendFormat": "Time for HR Eval Task (secs)"
    }
   ]
  },
  {
   "title": "Completed vs Running",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "kie_server_process_instance_running_total{container_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",}",
     "legendFormat": "Started Evaluations"
    },
    {
     "expr": "kie_server_process_instance_completed_total{container_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",status=\"2\",}",
     "legendFormat": "Completed Evaluations"
    }
   ]
  },
  {
   "title": "PM Tasks Status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "kie_server_task_added_total{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"PM Evaluation\",}",
     "legendFormat": "Openned PM Evals"
    },
    {
     "expr": "kie_server_task_completed_total{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"PM Evaluation\",}",
     "legendFormat": "Completed PM Evals"
    }
   ]
  },
  {
   "title": "HR Evals Tasks",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "kie_server_task_added_total{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"HR Evaluation\",}",
     "legendFormat": "Openned HR Evals"
    },
    {
     "expr": "kie_server_task_completed_total{deployment_id=\"evaluation_2.0.0-SNAPSHOT\",process_id=\"evaluation\",task_name=\"HR Evaluation\",}",
     "legendFormat": "Completed HR Evals"
    }
   ]
  }
 ]
}